Projects with JSON Files
breatheco-de/projects pull request #49
Opened 2019-08-26 01:54 UTC by haydavid23

2019-08-27 18:56 UTC, alesanchezr commented
@haydavid23 why is it giving conflicts? Did you modify the info.json files?

2019-08-27 19:26 UTC, haydavid23 commented
@alesanchezr I created a new folder ("projects") inside the "P" folder with all of the project as JSON. I noticed that all of the conflicting files path are incorrect. the path for career-support should be : p/**CSS/**career-support/xxx/xxx.json AND  the path for final-project should be : p/final-project/**full-stack**/web-development/wireframes/info.json. 

was the project modified after I made the fork???

2019-08-27 19:46 UTC, haydavid23 commented
@alesanchezr . I dont know what happened, but it appears that I changed the location of career support and final project. I will fix it the issue. give me a sec

2019-08-27 19:55 UTC, haydavid23 commented
. try again .. i fixed it

2019-08-28 03:42 UTC, alesanchezr requested changes

2019-08-28 03:42 UTC, alesanchezr commented on p/test.js
> +fs.readdirSync("./css/beginner").forEach(e=>projects.push(String(e)))
Porque estas buscando en carpetas en particular? estos nombres no pueden estar hardcoded.

Tenemos que sentarnos porque el algoritmo no esta haciendo exactamernte lo que que yo queria.

2019-08-28 11:01 UTC, haydavid23 commented on p/test.js
> +fs.readdirSync("./css/beginner").forEach(e=>projects.push(String(e)))
:(   ok.....  yo manana y el viernes voy a estar todo el dia en la academia.

2019-08-28 15:00 UTC, closed without merging